login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("main_website.urls")),
    path("password_reset/done", auth_views.PasswordResetDoneView.as_view(template_name="users/password/password_reset_done.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'),  name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/urls.py
from django.urls import path
from . import views
app_name = "main_app"
urlpatterns = [
    path("", views.home, name="home")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("account_type", views.profile_info, name="account_type"),
    path("login", views.login_view, name="login"),
    path("create", views.create_account, name="create"),
    path("logout", views.logout_view, name="logout"),
    path("image_upload", views.image_upload, name="image_upload"),
    path("create_property_account", views.create_property_account, name="create_property_account"),
    path("student_info", views.index, name="student_info"),
    path("student_account", views.student_details, name="student_details"),
    path("property_account", views.property_account, name="property_account"),
    path("account_creation_type", views.account_creation_type, name="account_creation_type"),
    path("register_property_owner", views.register_property_owner, name="register_property_owner"),
    path("id_upload", views.id_upload, name="id_upload"),
    path("view_id_document", views.view_id_document, name="view_id_document"),
    path("property_owner_profile", views.property_owner_profile, name="property_owner_profile"),
    path("add_property", views.add_property, name="add_property"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("edit_student_profile", views.edit_student_profile, name="edit_student_profile"),
    path("get_all_property", views.properties, name="get_all_property"),
    path("property/<int:id>", views.property_profile, name="property" ),
    path("edit_property_account", views.edit_property_account, name="edit_property_account"),
    path("view_property_owner/<int:number>", views.owner_view, name="owner_view"),
    path("delete_property/<int:number>", views.delete_property, name="owner_delete"),
    path("edit_property/<int:number>", views.edit_property, name="edit_property"),
    path("properties/<str:property_type>", views.view_properties_filter, name="view_properties_filter"),
    path("add_property", views.add_property, name="add_property"),
    path("property_view/<int:id>", views.view_property_as_student, name="view_property_as_student"),
    path("book_room/<int:id>", views.book_room, name="book_room"),
]

main_website/models.py
from django.db import models

# Create your models here.

main_website/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "main_website/home.html")

main_website/templates/main_website/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SPC HLALA NATHI</title>

<!-- ----favicon------- -->
<link rel="shortcut icon" type="image/png" href="Icons/spcFavicon.png">

<!-- ------Style.css------ -->
<link rel="stylesheet" href="{% static 'users/styles.css' %}" >

<!-- -------Font links------- -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">

</head>
<body class="bodyPadding">
    <!-- ------nav bar---- -->
    <nav class="navBar">
        <a class="spcLogoLink" href="new index.html">
            <img src="{% static 'main_website/logo.png' %}" class="spcLogo" alt="SPC logo">
          </a>

          <ul class="navBarRightPanel">
            <il>
                <a href="{% url 'main_app:home' %}" class="navItem activeLink">HOME</a>
            </il>
          
            <il >
                <a href="{% url 'users:student_details' %}" class="navItem">STUDENT</a>
            </il>
          
            <il>
                <a href="{% url 'users:property_account' %}" class="navItem">PROPERTY</a>
            </il>
            <il>
                <a href="new log in.html" alt="AccountIcon">
                    <img src="{% static 'main_website/orange account icon.png' %}" class="accountIcon" alt="account Icon">
                </a>
                </il>
            </il>
        </ul>
    </nav>
    {% for message in messages %}
    <div class="message {{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    <!-- -------Search section-------- -->
    <section class="searchSection">
        
            <input class="searchBox" type="search" name="searchType" placeholder="Search accommodation">
            <button type="submit" class="searchButton">
                <img class="searchIcon" src="{% static 'main_website/searchIcon.svg' %}"> 
            </button>
            
        
    
        <div class="quickSearch">
            <ul class="searchList">
                <li class="searchItems">Accommodation type 
                    <img class="searchDropdown"  src="{% static 'main_website/dropdown arrow.png' %}">
                </li>

                <li class="searchItems">Varsity 
                    <img class="searchDropdown"  src="{% static 'main_website/dropdown arrow.png' %}">
                </li>

                <li class="searchItems">Gender 
                    <img class="searchDropdown"  src="{% static 'main_website/dropdown arrow.png' %}">
                </li>
            </ul>

            <button class="quickSearchButton" type="Search" >Search</button>
        </div>
    </section>

    <!-- -------header section------- -->
    
    <section>
        <div class="headerBackground"></div>
        <h1 class="headerText">We have an <br>
            accommodation<br> 
            ready for you</h1>
    </section>

    <!-- -------Our properties------ -->

    <section>
        <h2 class="sectionHeader">Our Properties</h2>

        <div class="threeContainerFlexBox">
            <a href="#">
                <div class="flexItem">
                    <div class="boxImage"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">Apartments</h2>
                    </div>
                    
                </div>
            </a>

            <a href="#">
                <div class="flexItem">
                    <div class="boxImage2"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">Cummunes</h2>
                    </div>
                    
                </div>
            </a>

            <a href="#">
                <div class="flexItem">
                    <div class="boxImage3"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">High flats</h2>
                    </div>
                    
                </div>
            </a>

        </div>
    </section>

    <!-- -------Student community------- -->
    <section>
        <h2 class="sectionHeader studentCommunity">Student Community</h2>

        <div class="threeContainerFlexBox">

            <a href="#">
                <div class="flexItem">
                    <div class="boxImage4"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">Textbooks</h2>
                    </div>
                    
                </div>
            </a>
            
            <a href="#">
                <div class="flexItem">
                    <div class="boxImage5"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">Tutoring</h2>
                    </div>
                    
                </div>
            </a>
            
            <a href="#">
                <div class="flexItem">
                    <div class="boxImage6"></div>
    
                    <div class="blackBox">
                        <h2 class="boxText">Career Coach</h2>
                    </div>
                    
                </div>
            </a>
           
        </div>

    </section>

    <!-- -----advert section----- -->
    <section>
        <div class="advertSection"></div>
    </section>

     <!-- -----Add property----- -->
     <section>
         <div class="propertySignIn">
             <h2>Properties owners must Sign In to add a property</h2>
             <a class="SignInLink" href="#">Sign In</a>
         </div>
     </section>
     <!-- -----footer----- -->
     <footer class="footerBackground">
         <div class="footerHeader">
             <a href="new index.html">
                <img class="footerLogo" src="{% static 'main_website/logo.png' %}">
             </a>
           

            <div class="footerSocialMediaLinks">
                <a href="#"> <img class="SocialMediaIcon" src="{% static 'main_website/facebookIcon.png' %}"></a>
                <a href="#"> <img class="SocialMediaIcon" src="{% static 'main_website/instagramIcon.png' %}"></a>
            </div>
         </div>

<ul class="footerList">
    <a href="#">
        <li class="footerListItem">About us</li>
    </a>


    <a href="#">
        <li class="footerListItem">FAQ</li>
    </a>

    <a href="#">
        <li class="footerListItem">Contact us</li>
    </a>

    <a href="#">
        <li class="footerListItem">list your accommodation</li>
    </a>

    <a href="#">
        <li class="footerListItem">Advertising</li>
    </a>
    
</ul>

<p class="footerFooter">Student placement corporation | 2021</p>

     </footer>
</body>
</html>
{% if Not_a_student %}

<h4>{{Not_a_student}}</h4>
{% endif %}
<h1>Home</h1>
{% if student_logged_in %}
  <p style="color:red;">{{student_logged_in}} <a href="{% url 'users:logout' %}">logout</a></p>
{% endif %}

main_website/templates/main_website/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'main_website/styles.css' %}" rel="stylesheet">

    <title>Document</title>
</head>

<body>
    
    <nav>
        <a href="{% url 'users:account_type' %}">Profile</a>
        <a href="{% url 'main_app:home' %}">Home</a>
        <a href="{% url 'users:student_details' %}">Student</a>
        <a href="{% url 'users:property_account' %}">Property</a>
    </nav>
    {% block body %}{% endblock %}
   
</body>

</html>