login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls")),
    path("", include("main_website.urls")),
    path("password_reset/done", auth_views.PasswordResetDoneView.as_view(template_name="users/password/password_reset_done.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password/password_reset_complete.html'),  name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_website/urls.py
from django.urls import path
from . import views
app_name = "main_app"
urlpatterns = [
    path("", views.home, name="home")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("account_type", views.profile_info, name="account_type"),
    path("login", views.login_view, name="login"),
    path("create", views.create_account, name="create"),
    path("logout", views.logout_view, name="logout"),
    path("image_upload", views.image_upload, name="image_upload"),
    path("create_property_account", views.create_property_account, name="create_property_account"),
    path("student_info", views.index, name="student_info"),
    path("student_account", views.student_details, name="student_details"),
    path("property_account", views.property_account, name="property_account"),
    path("account_creation_type", views.account_creation_type, name="account_creation_type"),
    path("register_property_owner", views.register_property_owner, name="register_property_owner"),
    path("id_upload", views.id_upload, name="id_upload"),
    path("view_id_document", views.view_id_document, name="view_id_document"),
    path("property_owner_profile", views.property_owner_profile, name="property_owner_profile"),
    path("add_property", views.add_property, name="add_property"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path("edit_student_profile", views.edit_student_profile, name="edit_student_profile"),
    path("get_all_property", views.properties, name="get_all_property"),
    path("property/<int:id>", views.property_profile, name="property" ),
    path("edit_property_account", views.edit_property_account, name="edit_property_account"),
    path("view_property_owner/<int:number>", views.owner_view, name="owner_view"),
    path("delete_property/<int:number>", views.delete_property, name="owner_delete"),
    path("edit_property/<int:number>", views.edit_property, name="edit_property"),
    path("properties/<str:property_type>", views.view_properties_filter, name="view_properties_filter"),
    path("add_property", views.add_property, name="add_property"),
    path("property_view/<int:id>", views.view_property_as_student, name="view_property_as_student"),
    path("book_room/<int:id>", views.book_room, name="book_room"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IntegerField
from phonenumber_field.modelfields import PhoneNumberField

STUDENT_GENDER = (
    ("MALE", "Male"),
    ("FEMALE", "Female"),
    ("OTHER", "Other")
)
class Student(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    gender = models.CharField(max_length=6, choices=STUDENT_GENDER)
    phone_number = PhoneNumberField()


class Profiles(models.Model):
    profile_picture = models.ImageField(upload_to="images/", null=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)


class Identity(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    document = models.FileField(upload_to="documents/", null=True)


PROPERTY_CHOICES = (
        ("COMMUNE", "Commune"),
        ("APARTMENT", "Apartment"),
        ("FLAT", "flat")
)
UNIVERSITY_CHOICES = (
    ("UJ1", "UJ(APK)"),
    ("UJ2", "UJ(APB)"),
    ("UJ3", "UJ(DFC)"),
    ("UJ4", "UJ(  SWC)"),
    ("NWU1", "NWU-Mafikeng campus"),
    ("NWU2", "NWU-Vaal campus"),
    ("NWU3", "NWU-Potchefstroom campus"),
    ("TUT", "TUT"),
    ("WITS", "WITS"),
    ("UP", "WITS"),
    ("CUT", "CUT"),
    ("VUT", "VUT"),
    ("UWC", "UWC"),
    ("UFS", "UFS"),
)


class AddProperty(models.Model):
    id = models.AutoField(primary_key=True)
    main_picture = models.ImageField(upload_to="images/", null=False)
    room_picture = models.ImageField(upload_to="images/", null=True)
    kitchen_picture = models.ImageField(upload_to="images/", null=True)
    study_room_picture = models.ImageField(upload_to="images/", null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property_name = models.CharField(max_length=25)
    phone_number = PhoneNumberField()
    email = models.EmailField()
    property_type = models.CharField(max_length=9, choices=PROPERTY_CHOICES)
    university_catered = models.CharField(max_length=4, choices=UNIVERSITY_CHOICES)
    address = models.TextField()
    province = models.CharField(max_length=20)
    laundromat = models.BooleanField()
    security = models.BooleanField()
    hot_water = models.BooleanField()
    unlimited_wifi = models.BooleanField()
    transport = models.BooleanField()
    free_electricity = models.BooleanField()
    single_male = models.IntegerField()
    single_female = models.IntegerField()
    sharing_female = models.IntegerField()
    sharing_male = models.IntegerField()
    discription = models.TextField()
    price = models.FloatField()
    accreditation_letter = models.FileField(upload_to="documents/", null=True)
    lease = models.FileField(upload_to="documents/", null=True)


FUNDING = (
        ("NSFAS", "NSFAS"),
        ("BURSARY", "Bursary"),
        ("SELF FUNDED", "Self Funded ")
)

ROOM_TYPE = (
    ("SHARING", "Sharing"),
    ("SINGLE", "Single")
)
STATUS = (
    ("ACCEPTED", "Accepted"),
    ("DECLINED", "Declined"),
    ("PENDING", "Pending"),
)


class Bookings(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(AddProperty, on_delete=models.CASCADE)
    funding = models.CharField(max_length=11, choices=FUNDING)
    room_type = models.CharField(max_length=7, choices=ROOM_TYPE)
    status = models.CharField(max_length=8, choices=STATUS)

users/views.py
from django.core.mail.message import ADDRESS_HEADERS
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User, Permission
from django.contrib.auth import authenticate, logout, login
from .models import AddProperty, Student, Profiles, Identity, Bookings
from .forms import UploadPicture, UploadID, UploadBursaryLetter, UploadProofOfRegistration, PropertyGeneralInfo
from .forms import AddPropertyForm, StudentAdditionalForm, EditPropertyAccount, ApplicationForm
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.contenttypes.models import ContentType
from django.db import IntegrityError
from django.contrib.auth.forms import PasswordResetForm
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm


def add_permissions(permissions):
    for permission in permissions:
        try:
            content_type = ContentType.objects.get_for_model(User)
            Permission.objects.create(
                codename=permission,
                content_type=content_type,
            )
        except IntegrityError:
            pass


def create_user_account(user_name, name, email, password, last_name, phone_number, gender):
    """Creates a user  using name, email and password"""
    user = User.objects.create_user(user_name, email, password)
    user.first_name = name
    user.last_name = last_name
    user.save()
    student_permissions = ["view_property", "apply_for_resident", "edit_student_information",
                           "view_student_information", "upload_id", "book_room"]
    add_permissions(student_permissions)
    for permission_name in student_permissions:
        permission = Permission.objects.get(codename=permission_name)
        user.user_permissions.add(permission)
    user_info = Student(user=user, phone_number=phone_number, gender=gender)
    user_info.save()


def edit_property_owner_account(user, property_name, email, phone_number):
    """edits the details of the property owner"""
    user.first_name = property_name
    user.email = email
    user.save()
    # the phone number part
    user.student.phone_number = phone_number
    user_infor = user.student
    user_infor.save()
    

def create_property_owner_account(user_name, property_name, email, password, phone_number):
    """Create a property_owner user account with its own permission"""
    user = User.objects.create_user(user_name, email, password)
    # always remember first name is the property_name
    user.first_name = property_name
    # create a permission if they are not there
    property_owner_permissions = ["view_property_account", "edit_property_account", "create_property", "view_property",
                                  "edit_property", "view_student_application"]
    add_permissions(property_owner_permissions)
    # adding the permissions to this users
    for permission_name in property_owner_permissions:
        permission = Permission.objects.get(codename=permission_name)
        user.user_permissions.add(permission)
    # saving user with all the permissions of property Owner
    user.save()
    # saving property owners phone number
    user_info = Student(user=user, phone_number=phone_number)
    user_info.save()

# route to determine which type of user to create_user


def account_creation_type(request):
    return render(request, "users/account_creation_type.html")


@login_required(login_url="/users/login")
@permission_required("auth.create_property")
def add_property(request):
    if request.method == "POST":
        form_data = AddPropertyForm(request.POST, request.FILES)
        if form_data.is_valid():
            property = form_data.save(commit=False)
            property.user = request.user
            property.save()
            return HttpResponseRedirect(reverse("users:property_owner_profile"))
        else:
            form = AddPropertyForm()
            return render(request, "users/add_property.html", {
                "form": form,
            })
    form = AddPropertyForm()
    return render(request, "users/add_property.html", {
        "form": form,
    })

@login_required(login_url="users/login")
@permission_required("auth.upload_id")
def id_upload(request):
    """uploads the documents of the user"""
    if request.method == 'POST':
        form = UploadID(request.POST, request.FILES)
        if form.is_valid():
            # saves the id document of student_
            save_id_document = Identity(user=request.user, document=form.cleaned_data["id_document"])
            save_id_document.save()
            # returning user to their profile
            return render(request, "users/index.html", {
                "id_upload_message": "You have successfully uploaded your ID",
                "UploadPicture": UploadPicture(),
                "bursary_letter": UploadBursaryLetter(),
                "proof_of_registration": UploadProofOfRegistration,
                "id": UploadID,
            })
    else:
        return HttpResponseRedirect("users:student_account")


@login_required(login_url="/users/login")
def view_id_document(request):
    return render(request, "users/view_id_document.html", {
        "url_p": request.user.identity.document.url,
    })


@login_required(login_url="/users/login")
def image_upload(request):
    """saves the file"""
    if request.method == 'POST':
        # getting the user inform
        form = UploadPicture(request.POST, request.FILES)
        if form.is_valid():
            # don't forget to delete the current user image b4 updating
            create_user_profile = Profiles(user=request.user, profile_picture=form.cleaned_data["profile_picture"])
            create_user_profile.save()
            print(request.user.profiles.profile_picture.path)
            # checking to see if the image is indeed save
    return HttpResponseRedirect(reverse("users:student_info"))
# Create your views here.


def profile_info(request):
    # route for for when the user is logged in as Student
    user_student_account = request.user.has_perm("auth.view_student_information")
    property_owner_account = request.user.has_perm("auth.view_property_account")
    if user_student_account:
        return HttpResponseRedirect(reverse("users:student_info"))
        # don't forget the on when the property owner is logged in
    elif property_owner_account:
        return HttpResponseRedirect("users:property_owner_profile")
    else:
        # when no one is logged in
        return HttpResponseRedirect(reverse("users:login"))


@permission_required("auth.view_student_information")
def index(request):
    # checking the gender
    return render(request, "users/index.html", {
        "UploadPicture": UploadPicture(),
        "bursary_letter": UploadBursaryLetter(),
        "proof_of_registration": UploadProofOfRegistration,
        "id": UploadID,
    })


@login_required(login_url="/users/login")
def student_details(request):
    user_student_permission = request.user.has_perm("auth.view_student_information")
    if user_student_permission:
        return HttpResponseRedirect(reverse("users:student_info"))
    else:
        return render(request, "main_website/home.html", {
                "Not_a_student": "You have logged in with a Property Owner account"
                                 ", please sign out and log in with ur user account",
            })


def login_view(request):
    """deals with what happens when the user visits the login page"""
    if request.method == "POST":
        username = request.POST["user_name"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)

        if user is not None:
            # log the user in , if the user credentials are valid
            login(request, user)
            # check if user is a student or property owner
            is_student = user.has_perm("auth.view_student_information")
            is_property_owner = user.has_perm("auth.view_property_account")
            if is_student:
                # when the user is from student account
                return HttpResponseRedirect(reverse("users:student_info"))
            elif is_property_owner:
                # when user is a property owner
                return HttpResponseRedirect(reverse("users:property_owner_profile"))
            else:
                return HttpResponseRedirect(reverse("users:login"))
        else:
            return render(request, "users/login.html", {
                "message": "Your username and password do not match"
            })
    return render(request, "users/login.html")


def create_account(request):
    """For students"""
    # if user has registered successfully
    if request.method == "POST":
        # getting student information from the form
        student_form = StudentAdditionalForm(request.POST)
        # getting the stud
        if student_form.is_valid():
            # getting user info
            user_name = student_form.cleaned_data['user_name']
            first_name = student_form.cleaned_data['name'].title()
            email = student_form.cleaned_data['email']
            password = student_form.cleaned_data['password']
            last_name = student_form.cleaned_data['last_name'].title()
            phone_number = student_form.cleaned_data['phone_number']
            gender = student_form.cleaned_data['gender']
            try:
                print("creating user...")

users/templates/users/account_creation_type.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'users/styles.css' %}" rel="stylesheet">
    <title>Choose account</title>

<!-- -- ----favicon------- -->
<link rel="shortcut icon" type="image/png" href="Icons/spcFavicon.png">

<!-- ------Style.css------ -->
<link rel="stylesheet" href="{% static 'users/styles.css' %}">

<!-- -------Font links------- -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;700&display=swap" rel="stylesheet">

</head>
<body>

    <!-- --------Choose Account type------ -->

    <section class="chooseAccountBox">

        <h1 class="logInHeader">Choose account type</h1>

        <a href="{% url 'users:create' %}" class="accountLink">
            Student Account
        </a>

        <a href="{% url 'users:create_property_account' %}" class="accountLink">
            Property Account
        </a>
    </section>

</body>
</html>

users/templates/users/book_room.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        Confirm booking at {{property.property_name}}
        <img href="{{student.profiles.profile_picture.url}}">
        <div>
            Gender: {{student.student.gender}}
        <form method="POST" action="{% url 'users:book_room' property.id %}">
            {% csrf_token %}
            <div>
                <label>Funding</label>
                {{application.funding}}
            </div>
            <div>
                {{application.room_type}}
            </div>
            <button>book</button>
        </form>
        </div>
        
    </div>
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'users/styles.css' %}" rel="stylesheet">
  <title>{{request.user.first_name}}'s Profile</title>
  <link rel="shortcut icon" type="image/png" href="Icons/spcFavicon.png">

  <!-- ------Style.css------ -->
  <link rel="stylesheet" href="new style.css">

  <!-- -------Font links------- -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
    {% if request.user.profiles.profile_picture.url %}
      .profilePicture{
      background-image: url("{{ request.user.profiles.profile_picture.url }}");
      background-repeat:no-repeat;
      background-size:cover;
      background-position:right;
      height:350px;
      width:377px;

      border-radius:10px;
      outline:3px solid #FFB200;
    }
    {% elif request.user.student.gender == "MALE"%}
    .profilePicture{
      background-image: url("/static/images/maleAvatar.jpg");
      background-repeat:no-repeat;
      background-size:cover;
      background-position:right;
      height:350px;
      width:377px;
      outline:3px solid #FFB200;
      border-radius:10px;
    };
    {% elif request.user.student.gender == "FEMALE"%}
    .profilePicture{
      background-image: url("/static/images/femaleAvatar.jpg");
      background-repeat:no-repeat;
      background-size:cover;
      background-position:right;
      height:350px;
      width:377px;
      outline:3px solid #FFB200;
      border-radius:10px;
    };
    {% endif %}
  </style>
</head>
<body class="bodyPadding">
  <!--navbar-->
  <nav class="navBar">
    <a class="spcLogoLink" href="new index.html">
        <img src="{% static 'main_website/logo.png' %}" class="spcLogo" alt="SPC logo">
      </a>

      <ul class="navBarRightPanel">
        <il>
            <a href="{% url 'main_app:home' %}" class="navItem">HOME</a>
        </il>
      
        <il >
            <a href="{% url 'users:student_details' %}" class="navItem activeLink">STUDENT</a>
        </il>
      
        <il>
            <a href="{% url 'users:property_account' %}" class="navItem">PROPERTY</a>
        </il>
        <il>
            <a href="new log in.html" alt="AccountIcon">
                <img src="{% static 'main_website/orange account icon.png' %}" class="accountIcon" alt="account Icon">
            </a>
            </il>
        </il>
    </ul>
</nav>

</div>
</section>
  <!-- --------hamburger javascript---- -->
  <script>
    const navBarMobile = document.querySelector(".navBarMobile");
    const menuItems = document.querySelectorAll(".menuItem");
    const hamburger= document.querySelector(".hamburger");
    const closeMenu= document.querySelector(".closeMenu");
    const hamburgerMenu = document.querySelector(".hamburgerMenu");

    function toggleMenu() {
    if (navBarMobile.classList.contains("showMenu")) {
        navBarMobile.classList.remove("showMenu");
        closeMenu.style.display = "none";
        hamburgerMenu.style.display = "block";
    } else {
        navBarMobile.classList.add("showMenu");
        closeMenu.style.display = "block";
        hamburgerMenu.style.display = "none";
    }
    }

    hamburger.addEventListener("click", toggleMenu);
</script>

<!--------------------------Student Account section------------------------->
<section>
  <h2 class="sectionHeader studentDetailsHeader">Student Account</h2>
  
  <!--delete-->
  <div class="studentInformationHeader">
      <div class="profilePictureDiv">
          <div class="profilePicture">

          </div>
          <form action="{% url 'users:image_upload' %}" enctype="multipart/form-data" method="post"></form>
            <div class="uploadProfilePicture">
            
            {% csrf_token %}
            <label class="custom-file-upload uploadProfilePicture">
              {{UploadPicture}}
              </label>
              <div class="savePictureDiv">
                <button class="custom-file-upload saveProfilePicture">Save profile picture</button>
            </div>
            </form>

              upload profile picture
          </div>

      </div>

      <div class="rightInformationPanel">
          <div>
              <h1 class="studentName">{{request.user.first_name}}</h1>   
                <h3 class="studentLastName">{{request.user.last_name}}</h3>
          </div>
      </div>

      <div class="studentEditButtons">
          <button class="logInButton signUpProperties " >
              <a href="{% url 'users:logout' %}" class="submitLink">Sign Out</a>
          </button>

          <button class="logInButton signUpProperties editProfileWidth" >
              <a href="{% url 'users:edit_student_profile' %}" class="submitLink">Edit Profile</a>
          </button>
      </div>

  </div>

</section>
<!-- ------student details------- -->
<section class="studentDetailsSection">
  <h2 class="sectionHeader studentDetailsHeader">Student Details</h2>

  <div class="studentDetailsFlexBox">
      <div class="studentImportantInformationLeftPanel">

          <div class="informationDiv">
              <p>Username</p>
              <div class="infoAboutStudent">
                {{request.user.username}}
              </div>
          </div>

          <div class="informationDiv">
              <p>Email</p>
              <div class="infoAboutStudent">
                {{request.user.email}}
              </div>
          </div>

          <div class="informationDiv">
              <p>Cellphone number</p>
              <div class="infoAboutStudent">
                {{request.user.student.phone_number}}
              </div>
          </div>
      </div>

      <div class="studentImportantInformationRightPanel">
          <div class="informationDiv">
              <p>Name</p>
              <div class="infoAboutStudent infoAboutStudentRight">
                {{request.user.first_name}}
              </div>
          </div>

          <div class="informationDiv">
              <p>Last Name</p>
              <div class="infoAboutStudent infoAboutStudentRight">
                {{request.user.last_name}}
              </div>
          </div>
          <div class="informationDiv ">
            <p>Gender</p>
            <div class="infoAboutStudent  infoAboutStudentRight">
                {{request.user.student.gender}}
            </div>
      </div>

  </div>
</section>
<section>
  <h2 class="sectionHeader ">Student Documents</h2>

  <p class="studentDocumentBrief">The documents uploaded by the student will not be shared with any property 
      owner or anyone. They will be used to secure a room in a booked accommodation.</p>

      <div class="suggestionDiv">
          <img class="suggestionIcon" src="{% static 'main_website/newIdeaIcon.png' %}">

          <p class="studentDocumentBrief">Upload your documents to avoid carrying them when you move in</p>
      </div>

      <div class="documentsFlexBox">
          <div>
              <div class="documentDiv">
                  <h3 class="documentHeader">Identification card (ID)</h3>
                  <img class="documentIcon" src="{% static 'main_website/document icon.png' %}">
              </div>

              <div class="documentButtonsDiv">
                  <a href="#" class="documentUpload">
                      <input type="file" placeholder="Upload">
                  </a>

                  <a href="#" class="documentPreview">
                      Pre View
                  </a>
              </div>    
          </div>


          <div>
              <div class="documentDiv">
                  <h3 class="documentHeader">NSFAS/ Bursary letter</h3>
                  <img class="documentIcon" src="{% static 'main_website/document icon.png' %}">
              </div>

              <div class="documentButtonsDiv">
                  <a href="#" class="documentUpload">
                      <input type="file" placeholder="Upload">
                  </a>

                  <a href="#" class="documentPreview">
                      Pre View
                  </a>
              </div>    
          </div>


          <div>
              <div class="documentDiv">
                  <h3 class="documentHeader">Proof of registration</h3>
                  <img class="documentIcon" src="{% static 'main_website/document icon.png' %}">
              </div>

              <div class="documentButtonsDiv">
                  <a href="#" class="documentUpload">
                      <input type="file" placeholder="Upload">
                  </a>

                  <a href="#" class="documentPreview">
                      Pre View
                  </a>
              </div>    
          </div>


      </div>


</section>

</body>
</html>

<h1>{{request.user.username}}</h1>
<form action="{% url 'users:image_upload' %}" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {{UploadPicture}}
  <input type="submit" value="Upload">
</form>
  {% if id_upload_message %}
    <p>{{id_upload_message}}</p>
  {% endif %}

</ul>
<hr>
<h2>Documents</h2>
<div>
  <div>
    <label>Identification (ID)</label>
    <div>
      <form action="{% url 'users:id_upload' %}" enctype="multipart/form-data" method="post">
      {{id}}
      {% csrf_token %}
      <input type="submit" value="upload">
        <a href="{% url 'users:view_id_document' %}">View Document</a>
      </form>
    <div>
  <div>
    <div>
      <label>Busary Letter</label>
      <div>
        {{bursary_letter}}
        <input type="submit" value="upload">
      </div>
    </div>
    <div>
      <label>Proof of registration</label>
        <div>
          {{proof_of_registration}}
          <input type="submit" value="upload">
        </div>
    </div>

</div>
<a href="{% url 'users:logout' %}">log Out</a>

users/templates/users/view_properties.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'users/styles.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bodyPadding">

    </nav> <!-- ------nav bar---- -->
    <nav class="navBar">
      <a class="spcLogoLink" href="index.html">
          <img src="{% static 'main_website/logo.png' %}" class="spcLogo" alt="SPC logo">
        </a>

        <ul class="navBarRightPanel navBarMobile">

          <li>
              <div class="searchDIV">
                  <input class="searchBox profileSearchBox menuItem" type="search" name="searchType" placeholder="Search accommodation">
                  <button type="submit" class="searchButton menuItem profileSearchIcon">
                      <img class="searchIcon  propertySearchIcon" src="Icons/searchIcon.svg"> 
                  </button>
              </div>
          </li>

          <il>
              <a href="{% url 'main_app:home' %}" class="navItem menuItem">HOME</a>
          </il>
        
          <il >
              <a href="{% url 'users:student_details' %}" class="navItem  hideStudent menuItem">STUDENT</a>
          </il>
        
          <il>
            <il>
                <a href="{% url 'users:property_account' %}" class="navItem showProperty activeLink menuItem">PROPERTY</a>
            </il>

          <il>
              <a href="{% url 'users:property_account' %}"  alt="AccountIcon">
                  <img src="{% static 'main_website/orange account icon.png' %}"  class="accountIcon" alt="account Icon">
              </a>
              </il>
          </il>
      </ul>

      <button class="hamburger">
          <img class="hamburgerMenu" src="icons/hamburgerMenu.svg">
          <img class="closeMenu" src="icons/closeMenu.svg">

      </button>
    </nav>
    {% if properties %}
        {% for property in properties %}
            <div class="editImageDiv homePagePropertyDiv">
                <img class="propertyImage homePagePropertyImage" src="{{property.main_picture.url}}">
            <div class="propertyName propertyNameHomePage">{{property.property_name}}</div>
            <div class="homePagePropertyPrice">
                R{{property.price}}
             </div>
            <div class="homePagePropertyDescription">
                description: {{property.discription}}
            </div>
                <a href="{% url 'users:view_property_as_student' property.id %}" class="uploadImageEdit2 homePagePropertyViewButton">View Property</a>
            </div>
        {% endfor %}
    {% else %}
        <div class=" shoeMesomething">
            THERE ARE NO PROPERTIES IN THIS SECTION :(
        </div>
    {%endif%}
</body>
</html>